In [ ]:
import pandas as pd

In [ ]:
pd.__version__

In [8]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is 3E11-2255

 Directory of C:\Users\mdeane\PythonDA\python-class\Lesson_4

23/05/2020  11:45 AM    <DIR>          .
23/05/2020  11:45 AM    <DIR>          ..
23/05/2020  09:34 AM    <DIR>          .ipynb_checkpoints
23/05/2020  11:45 AM           913,975 DataVisual.ipynb
23/05/2020  11:45 AM         3,451,125 lesson_4.ipynb
               2 File(s)      4,365,100 bytes
               3 Dir(s)  648,049,172,480 bytes free

In [10]:
df = pd.read_csv("../datasets/weatherAUS.csv", parse_dates=['Date'])

In [13]:
df.loc[df['Location'] == 'Sydney'].describe().T

,count,mean,std,min,25%,50%,75%,max
MinTemp,3334.0,14.865057,4.553641,4.3,11.0,14.9,18.7,27.6
MaxTemp,3335.0,23.002339,4.494638,11.7,19.6,22.8,26.0,45.8
Rainfall,3331.0,3.330231,9.895172,0.0,0.0,0.0,1.4,119.4
Evaporation,3286.0,5.187432,2.777407,0.0,3.2,4.8,7.0,18.4
Sunshine,3321.0,7.179374,3.810886,0.0,4.3,8.3,10.2,13.6
WindGustSpeed,2301.0,41.761408,13.007523,17.0,31.0,41.0,50.0,96.0
WindSpeed9am,3311.0,15.070674,7.079724,0.0,9.0,15.0,20.0,54.0
WindSpeed3pm,3312.0,19.335447,7.482554,0.0,15.0,19.0,24.0,57.0
Humidity9am,3323.0,68.229010,15.085355,19.0,58.0,69.0,80.0,100.0
Humidity3pm,3324.0,54.699158,16.293530,10.0,44.0,56.0,65.0,99.0
Pressure9am,3317.0,1018.346156,7.021571,986.7,1013.7,1018.6,1023.1,1039.0
Pressure3pm,3318.0,1016.018774,7.032211,989.8,1011.3,1016.3,1020.8,1036.7
Cloud9am,2771.0,4.181523,2.749578,0.0,1.0,5.0,7.0,9.0
Cloud3pm,2776.0,4.218660,2.641885,0.0,1.0,4.0,7.0,8.0
Temp9am,3333.0,17.819742,4.897177,6.4,13.8,18.2,21.7,36.5
Temp3pm,3333.0,21.533333,4.303737,10.2,18.4,21.3,24.5,44.7
RISK_MM,3337.0,3.319868,9.885066,0.0,0.0,0.0,1.4,119.4

In [14]:
from datetime import datetime

In [19]:
mask = ((df['Location'] == 'Sydney') & 
        (df['Date'] > datetime(2014, 12, 31)) & 
        (df['Date'] < datetime(2016, 1, 1)))

In [20]:
df.loc[mask].describe().T

,count,mean,std,min,25%,50%,75%,max
MinTemp,365.0,14.927397,4.693714,5.0,11.0,15.3,18.800,23.6
MaxTemp,365.0,23.146849,4.749068,13.4,19.7,22.6,26.300,40.9
Rainfall,365.0,3.666301,11.462586,0.0,0.0,0.0,1.400,119.4
Evaporation,355.0,5.201127,2.896481,0.0,3.0,5.0,7.000,14.6
Sunshine,362.0,7.049171,3.788284,0.0,4.3,8.0,10.075,13.4
WindGustSpeed,354.0,41.101695,12.774170,19.0,31.0,39.0,48.000,91.0
WindSpeed9am,364.0,14.934066,6.813618,2.0,9.0,15.0,19.000,54.0
WindSpeed3pm,364.0,19.373626,7.704813,2.0,15.0,19.0,24.000,46.0
Humidity9am,365.0,69.731507,15.543424,28.0,58.0,69.0,82.000,100.0
Humidity3pm,365.0,54.978082,16.556748,13.0,44.0,55.0,64.000,96.0
Pressure9am,365.0,1019.651507,7.049326,999.1,1014.8,1019.4,1024.400,1038.8
Pressure3pm,365.0,1017.430411,6.994738,997.2,1012.8,1017.5,1021.900,1036.0
Cloud9am,364.0,4.285714,2.712224,0.0,1.0,5.0,7.000,8.0
Cloud3pm,365.0,4.361644,2.594512,0.0,2.0,5.0,7.000,8.0
Temp9am,365.0,17.999452,5.119179,6.7,13.8,18.7,21.800,32.4
Temp3pm,365.0,21.624658,4.526163,11.7,18.5,21.3,24.600,40.7
RISK_MM,365.0,3.666301,11.462586,0.0,0.0,0.0,1.400,119.4

In [22]:
mask2 =  ((df['Date'] > datetime(2014, 12, 31)) & 
        (df['Date'] < datetime(2016, 1, 1)))

In [26]:
df.loc[mask2,'Evaporation'].isna().sum()

8463

In [29]:
# Let's normalise the columns
df.columns = [col.lower() for col in df.columns]
df.columns


df['year'] = df['date'].dt.year

In [30]:
df.loc[mask].describe().T

,count,mean,std,min,25%,50%,75%,max
mintemp,365.0,14.927397,4.693714,5.0,11.0,15.3,18.800,23.6
maxtemp,365.0,23.146849,4.749068,13.4,19.7,22.6,26.300,40.9
rainfall,365.0,3.666301,11.462586,0.0,0.0,0.0,1.400,119.4
evaporation,355.0,5.201127,2.896481,0.0,3.0,5.0,7.000,14.6
sunshine,362.0,7.049171,3.788284,0.0,4.3,8.0,10.075,13.4
windgustspeed,354.0,41.101695,12.774170,19.0,31.0,39.0,48.000,91.0
windspeed9am,364.0,14.934066,6.813618,2.0,9.0,15.0,19.000,54.0
windspeed3pm,364.0,19.373626,7.704813,2.0,15.0,19.0,24.000,46.0
humidity9am,365.0,69.731507,15.543424,28.0,58.0,69.0,82.000,100.0
humidity3pm,365.0,54.978082,16.556748,13.0,44.0,55.0,64.000,96.0
pressure9am,365.0,1019.651507,7.049326,999.1,1014.8,1019.4,1024.400,1038.8
pressure3pm,365.0,1017.430411,6.994738,997.2,1012.8,1017.5,1021.900,1036.0
cloud9am,364.0,4.285714,2.712224,0.0,1.0,5.0,7.000,8.0
cloud3pm,365.0,4.361644,2.594512,0.0,2.0,5.0,7.000,8.0
temp9am,365.0,17.999452,5.119179,6.7,13.8,18.7,21.800,32.4
temp3pm,365.0,21.624658,4.526163,11.7,18.5,21.3,24.600,40.7
risk_mm,365.0,3.666301,11.462586,0.0,0.0,0.0,1.400,119.4
year,365.0,2015.000000,0.000000,2015.0,2015.0,2015.0,2015.000,2015.0

In [34]:
#groupby to count nan for evaporation by year

In [44]:
g = df.groupby('year')
g.count().rsub(g.size(), axis=0)

,date,location,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustdir,windgustspeed,winddir9am,...,humidity3pm,pressure9am,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,raintoday,risk_mm,raintomorrow
year,,,,,,,,,,,,,,,,,,,,,
2007,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2008,0,0,9,4,17,325,318,447,446,90,...,20,94,93,356,366,17,13,17,0,0
2009,0,0,117,56,81,5591,6061,1575,1573,1282,...,206,1632,1633,5410,5647,141,168,81,0,0
2010,0,0,124,55,228,5602,5894,1277,1274,1373,...,159,1461,1453,5219,5364,173,146,228,0,0
2011,0,0,45,14,143,5625,5895,948,946,999,...,125,1516,1494,5690,5927,147,104,143,0,0
2012,0,0,40,18,150,5814,6287,802,797,1097,...,382,1334,1341,5630,5899,149,118,150,0,0
2013,0,0,48,24,162,6251,7409,804,778,1072,...,163,1354,1346,6581,6626,93,57,162,0,0
2014,0,0,51,27,219,7902,8832,1090,1088,1410,...,131,1954,1949,6878,6937,63,57,219,0,0
2015,0,0,43,31,142,8463,9165,927,908,1114,...,668,1989,1987,6593,7019,31,478,142,0,0
2016,0,0,76,64,167,9626,11705,988,988,990,...,1193,1816,1821,7343,8674,57,1082,167,0,0
2017,0,0,84,29,97,5644,6250,472,472,586,...,563,864,864,3957,4635,33,503,97,0,0